{% set name = "dask-geomodeling" %}
{% set version = "2.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 549d8682c2de8187c7f1d333ba779b6fe01f7678700ccaf9bc88d730bb990adb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - gdal
    - dask-core >=0.18
    - toolz
    - pandas >=0.19
    - geopandas >=0.4
    - pytz
    - numpy >=1.12
    - scipy >=0.19

test:
  imports:
    - dask_geomodeling
    - dask_geomodeling.core
    - dask_geomodeling.geometry
    - dask_geomodeling.raster

about:
  home: http://github.com/nens/dask-geomodeling
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: On-the-fly operations on geographical maps
  description: |
    dsk-geomodeling is a collection of classes that are to be stacked together to
    create configurations for on-the-fly operations on geographical maps.
  doc_url: http://dask-geomodeling.readthedocs.io/
  dev_url: http://github.com/nens/dask-geomodeling

extra:
  recipe-maintainers:
    - caspervdw
    - reinout
